// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}

type RegisterReq struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type RegisterResp struct {
	Msg string `json:"msg"`
}

type GetonestudentReq struct {
	Name string `form:"name"`
}

type GetonestudentResp struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
